# 1. Implement the single layer perceptron (SLP) for the OR and AND problem. Please make sure the followings:
### a)Activation function is threshold activation.
###b) Train the model for different learning rates (LR), where 0<LR<1. Train for 5 different learning rates and plot the training curve(epoch vs training accuracy).
### c) Weight initialization should be between -0.3 to 0.3

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

In [19]:
def generate(n):
  all_poss=[]
  for i in range(1<<n):
    c=i
    tmp=[]
    tmp.append(1)
    k=0
    while c>0:
      j=c%2
      tmp.append(j)
      c=int(c/2) 
      k+=1
    while k<n:
      tmp.append(0)
      k+=1  
    all_poss.append(tmp)
  return all_poss

def OR(arr):
  y=[]
  for row in arr:
    yi=0
    for i in range(1,len(row)):
      yi=yi|row[i]
    y.append(yi)
  return y

def AND(arr):
  y=[]
  for row in arr:
    yi=1
    for i in row:
      yi=yi&i
    y.append(yi)
  return y

#this is the program to check the accuracy of the weights whether they are adjusted correctly
def Accuracy(ins,outs,weights):
  count=0
  for X,Y in zip(ins,outs):
    predicted_y=np.matmul(X,weights)>0
    if predicted_y==Y:
      count+=1
  acc=100*(count/len(outs)) 
  return acc

#this is the program to run SLP    
#no. of times represent how many times we will run the loop with different learning rates
def SLP(X,Y,epochs,left,right,num_of_times):
  learning_rate=(right-left)/num_of_times
  lr=0
  colors=['m','b','y','g','r']
  for i in range(num_of_times):
    lr+=learning_rate
    accuracy=[]
    weights=np.random.uniform(-0.3,0.3,len(X[0]))
    for _ in range(epochs):
     for ins,outs in zip(X,Y):
       predict = ins@weights>0
       weights += [((lr * (outs-predict)))*i for i in ins]
     accuracy.append(Accuracy(X,Y,weights))
    y=[]
    #print(accuracy)
    print("for learning rate=",lr)
    for row in X:
      y.append((np.matmul(row,weights)>0)-0)
    print(y)    

### For OR

In [20]:
#FOR OR
nums=input("enter no. of features you want to add:")
X=generate(int(nums))#while genrating the input matrix I have also added the bias term initialy
print(X)
Y=OR(X)
print(Y)
epochs=int(input("enter no. of epochs you want to run:"))
SLP(X,Y,int(epochs),0,1,5)

enter no. of features you want to add:2
[[1, 0, 0], [1, 1, 0], [1, 0, 1], [1, 1, 1]]
[0, 1, 1, 1]
enter no. of epochs you want to run:10
for learning rate= 0.2
[0, 1, 1, 1]
for learning rate= 0.4
[0, 1, 1, 1]
for learning rate= 0.6000000000000001
[0, 1, 1, 1]
for learning rate= 0.8
[0, 1, 1, 1]
for learning rate= 1.0
[0, 1, 1, 1]


### For And

In [21]:
#FOR OR
nums=input("enter no. of features you want to add:")
X=generate(int(nums))#while genrating the input matrix I have also added the bias term initialy
print(X)
Y=AND(X)
print(Y)
epochs=int(input("enter no. of epochs you want to run"))
SLP(X,Y,int(epochs),0,1,5)


enter no. of features you want to add:2
[[1, 0, 0], [1, 1, 0], [1, 0, 1], [1, 1, 1]]
[0, 0, 0, 1]
enter no. of epochs you want to run10
for learning rate= 0.2
[0, 0, 0, 1]
for learning rate= 0.4
[0, 0, 0, 1]
for learning rate= 0.6000000000000001
[0, 0, 0, 1]
for learning rate= 0.8
[0, 0, 0, 1]
for learning rate= 1.0
[0, 0, 0, 1]


# 2)Implimenting Naive Bayes Classifier for classifying whether a person is suffering from breast cancer or not



In [ ]:
import sklearn
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer=sklearn.datasets.load_breast_cancer(return_X_y=False)

X=cancer.data
Y=cancer.target
# data = np.c_[cancer.data, cancer.target]
# columns = np.append(cancer.feature_names, ["target"])
# Data=pd.DataFrame(data, columns=columns)
# col=Data.columns
# X=Data[['mean radius', 'mean texture', 'mean perimeter', 'mean area','mean smoothness', 'mean compactness', 'mean concavity','mean concave points', 'mean symmetry', 'mean fractal dimension','radius error', 'texture error', 'perimeter error', 'area error','smoothness error', 'compactness error', 'concavity error','concave points error', 'symmetry error', 'fractal dimension error','worst radius', 'worst texture', 'worst perimeter', 'worst area','worst smoothness', 'worst compactness', 'worst concavity','worst concave points', 'worst symmetry', 'worst fractal dimension']]
# Y=Data['target']
print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [ ]:
#HERE WE WOULD BE USING GAUSSIAN NAIVE BAYES CONCEPT SINCE THE DATA IS IN A CONTINIOUS FORM
def classify_for_one(ins,outs,prob_of_yes,prob_of_no,x_0_mean,x_1_mean,x_0_varience,x_1_varience):
  yes=1 #this will tell probability given a dataset entry ins he has breast cancer
  no=1  #this will tell probability give a dataset entry ins he does not have breast cancer
  for xi in range(len(ins)):
    no*=(1/math.sqrt(2*(math.pi)*x_0_varience[xi]))*math.exp((-1/2)*((math.pow(ins[xi]-x_0_mean[xi],2))/(x_0_varience[xi])))
    yes*=(1/math.sqrt(2*(math.pi)*x_1_varience[xi]))*math.exp((-1/2)*((math.pow(ins[xi]-x_1_mean[xi],2))/(x_1_varience[xi])))

  Xgivenno=(no*prob_of_no)/((no*prob_of_no)+(yes*prob_of_yes))
  Xgivenyes=(yes*prob_of_yes)/((no*prob_of_no)+(yes*prob_of_yes))
  return Xgivenno,Xgivenyes

def prediction_n_accuracy(X,Y,prob_of_yes,prob_of_no,x_0_mean,x_1_mean,x_0_varience,x_1_varience):
  count=0
  for x,y in zip(X,Y):
    Xgivenno,Xgivenyes=classify_for_one(x,y,prob_of_yes,prob_of_no,x_0_mean,x_1_mean,x_0_varience,x_1_varience)
    if Xgivenno>Xgivenyes:
      if y==0:
        count+=1
    else:
      if y==1:
        count+=1 
  acc=100*(count/len(Y))
  return acc

X=cancer.data
Y=cancer.target
X_0=[]#X_0 & Y_0 will be storing the thoes values where y==0 that is the person is not suffering form breast cancer
Y_0=[]
X_1=[]#X_1 & Y_1 will be storing thoes values where y==1 that is the person who is suffering from breast cancer
Y_1=[]
for ins,outs in zip(X,Y):
  if outs == 1:
    X_1.append(ins)
    Y_1.append(outs)
  else:
    X_0.append(ins)
    Y_0.append(outs)  

prob_of_yes=len(Y_1)/len(Y)
prob_of_no=len(Y_0)/len(Y)

x_0_mean=np.mean(X_0,axis=0)
x_1_mean=np.mean(X_1,axis=0)

x_0_varience=np.var(X_0,axis=0)
x_1_varience=np.var(X_1,axis=0)
acc=prediction_n_accuracy(X,Y,prob_of_yes,prob_of_no,x_0_mean,x_1_mean,x_0_varience,x_1_varience)
print(acc,"%")


94.02460456942003 %
