# Part 1: Calculate the Mean, Median, Mode and Standard deviation

In [14]:
import pandas as pd
import numpy as np
import scipy as sy

## 1. Load the wine dataset from the given ‘wine.csv’ file into avariable (say data).



In [2]:
data=pd.read_csv('https://drive.google.com/uc?export=download&id=1EV_vQ1KSLiszmleCpGsFihloHNdimDRk')

##2. From the variable, extract the numerical information into a new variable, say scores.

In [3]:
scores=data[:].to_numpy()
print(scores)
print(scores.shape)
print(type(scores))

[[1.000e+00 1.423e+01 1.710e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.000e+00 1.320e+01 1.780e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.000e+00 1.316e+01 2.360e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [3.000e+00 1.327e+01 4.280e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [3.000e+00 1.317e+01 2.590e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [3.000e+00 1.413e+01 4.100e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
(178, 14)
<class 'numpy.ndarray'>


## 3. Calculate the row-wise,column-wise, and overall mean, median, mode, and standard deviation of the dataset. In this question write separate functions for each operation and pass the variable(scores) as the parameter to the function

In [20]:

def fun_mean(val):
    print("\n mean of score: ", np.mean(val))  
    print("\n mean of scores row wise: ",np.mean(val,axis=1))
    print("\n the size of row wise mean:",np.mean(val,axis=1).shape)
    print("\n mean of scores column wise :",np.mean(val,axis=0))
    print("\n the size of column wise mean: ",np.mean(scores,axis=0).shape)
fun_mean(scores)


 mean of score:  64.33398715850723

 mean of scores row wise:  [ 89.          85.36428571  95.91571429 117.96357143  64.97785714
 115.445      102.67571429 104.98428571  85.20142857  85.53285714
 119.4        101.86928571 104.35714286  92.26285714 121.60857143
 105.52285714 104.15        93.05642857 131.85142857  72.39142857
  68.56642857  66.22        84.84928571  82.92785714  71.10428571
  72.42357143  95.67142857 102.00785714  77.01214286  84.46142857
 103.28214286 119.84214286  81.82214286 101.62        89.84571429
  76.90071429  74.265       89.55285714  83.245       67.19714286
  69.02571429  84.23142857  89.20785714  59.74571429  74.60714286
  89.14857143  87.32214286  81.42        87.12214286 101.87714286
  92.32285714 100.96        96.79428571 110.33357143  87.88285714
  92.42142857  81.61714286 101.84642857 103.44357143  45.95285714
  58.93428571  42.69428571  55.23357143  40.06142857  36.27857143
  59.13214286  45.08        45.69714286  64.75428571  65.42285714
  72.9454285

In [5]:
def fun_median(val):
  print("\n median of score: ", np.median(val))  
  print("\n median of scores row wise: ",np.median(val,axis=1))
  print("\n the size of row wise median:",np.median(val,axis=1).shape)
  print("\n median of scores column wise :",np.median(val,axis=0))
  print("\n the size of column wise median: ",np.median(scores,axis=0).shape)

fun_median(scores)


 median of score:  2.6

 median of scores row wise:  [2.93  2.705 2.99  3.47  2.835 3.06  2.51  2.605 2.825 3.065 3.06  2.375
 2.68  2.955 3.15  2.865 2.76  2.785 3.06  3.065 3.085 3.085 2.745 2.5
 2.61  2.94  2.895 2.295 2.96  2.49  2.855 2.87  2.555 2.845 2.59  2.84
 2.73  2.48  2.52  3.285 3.22  2.84  3.405 2.82  3.    3.09  3.345 3.215
 2.75  2.99  2.91  2.795 3.5   2.86  2.75  2.87  3.1   2.92  3.135 1.885
 2.025 2.01  2.05  2.985 2.115 2.49  3.08  2.055 2.18  2.25  1.91  2.905
 2.12  3.095 2.715 1.96  2.015 2.375 2.155 2.7   2.34  2.365 2.1   2.165
 2.465 2.22  2.13  2.3   2.26  2.1   2.135 2.21  2.03  2.35  2.62  2.55
 2.19  2.525 3.145 2.84  2.2   1.95  2.51  2.03  2.1   2.41  2.075 2.14
 2.22  2.72  3.04  2.35  2.59  2.395 2.53  2.185 1.985 2.075 2.06  2.
 2.845 3.46  2.465 2.635 2.97  2.625 2.79  2.34  2.26  2.475 1.915 2.695
 2.355 2.68  2.125 2.33  2.77  2.82  2.595 2.785 2.755 2.515 2.86  2.675
 2.6   2.575 2.615 2.74  2.69  2.68  2.81  2.575 2.475 2.64  1.825 2.66
 2.69 

In [10]:
from scipy import stats
def fun_mode(val):
  print("\n  mode of score: ", stats.mode(val,axis=None)[0])  
  print("\n mode of scores row wise: ",stats.mode(val,axis=1)[0])
  #print("\n the size of row wise mode:",stats.mode(val,axis=1).shape)
  print("\n mode of scores column wise :",stats.mode(val,axis=0)[0])
  #print("\n the size of column wise mode: ",stats.mode(scores,axis=0).shape)

fun_mode(scores)


  mode of score:  [2.]

 mode of scores row wise:  [[0.28]
 [0.26]
 [0.3 ]
 [0.24]
 [0.39]
 [0.34]
 [0.3 ]
 [0.31]
 [0.29]
 [0.22]
 [0.22]
 [0.26]
 [0.29]
 [0.43]
 [0.29]
 [0.3 ]
 [0.33]
 [0.4 ]
 [0.32]
 [0.17]
 [0.24]
 [2.41]
 [0.27]
 [0.26]
 [2.61]
 [0.47]
 [0.34]
 [0.27]
 [0.37]
 [0.26]
 [0.29]
 [0.22]
 [0.42]
 [0.5 ]
 [0.29]
 [0.26]
 [0.34]
 [0.29]
 [0.28]
 [0.2 ]
 [0.34]
 [0.27]
 [3.56]
 [0.32]
 [3.  ]
 [0.3 ]
 [0.27]
 [0.21]
 [2.75]
 [0.32]
 [2.91]
 [0.22]
 [0.32]
 [0.39]
 [0.21]
 [0.2 ]
 [0.26]
 [0.31]
 [0.19]
 [0.28]
 [0.41]
 [2.02]
 [0.32]
 [0.19]
 [1.45]
 [0.37]
 [3.18]
 [2.  ]
 [0.42]
 [1.28]
 [0.37]
 [0.21]
 [0.27]
 [0.21]
 [0.13]
 [0.34]
 [0.24]
 [0.43]
 [0.35]
 [0.43]
 [2.  ]
 [2.2 ]
 [2.  ]
 [0.61]
 [0.22]
 [0.3 ]
 [0.43]
 [0.4 ]
 [0.48]
 [0.42]
 [0.52]
 [0.5 ]
 [0.58]
 [0.25]
 [0.17]
 [0.32]
 [0.14]
 [0.29]
 [0.24]
 [0.45]
 [0.26]
 [0.29]
 [0.34]
 [0.37]
 [0.32]
 [0.66]
 [0.37]
 [0.48]
 [0.39]
 [0.29]
 [0.24]
 [2.  ]
 [0.6 ]
 [0.42]
 [0.43]
 [0.52]
 [0.3 ]
 [1.61]
 [0.

In [11]:
def fun_standard_dev(val):
  print("\n standard deviation of score: ", np.std(val))  
  print("\n standard deviation of scores row wise: ",np.std(val,axis=1))
  print("\n the size of row wise standard deviation:",np.std(val,axis=1).shape)
  print("\n standard deviation of scores column wise :",np.std(val,axis=0))
  print("\n the size of column wise standard deviation: ",np.std(scores,axis=0).shape)
fun_standard_dev(scores)


 standard deviation of score:  208.61735837075227

 standard deviation of scores row wise:  [272.55228405 268.70559608 303.10665268 378.81001887 188.17135148
 371.19325702 330.17447004 331.44017301 267.29937913 267.22795575
 386.57283893 327.6191023  337.88934242 294.23431172 396.14504883
 335.23213606 327.5039538  289.03391253 430.22213098 216.23490282
 199.81955401 196.84977416 264.73135209 259.60233826 215.98563943
 212.4175103  305.78171801 328.94786326 233.95316003 264.72121524
 328.72666127 387.85388466 253.22526155 316.08254821 280.14150957
 235.17148708 225.16030552 282.70342998 260.9657227  194.79460895
 203.45974087 264.65517093 280.0907299  173.94259179 226.34901661
 276.21096507 272.3470847  251.87147374 271.05315038 322.33303843
 294.23693423 323.69762992 304.46018158 351.93182862 271.23081819
 286.47585512 248.15289626 324.98622963 328.81192022 133.32707272
 174.11304553 115.72010442 161.15119518 107.59680936  92.1801039
 173.38506041 128.20341209 130.25795887 192.056008

# Part 2: Calculate the pearson correlation and covariance matrix

##1. Take the ‘alcohol’ and ‘Proline’ as the features from the ‘wine.csv’ dataset and calculate the pearson correlation for the same.

In [15]:
print(sy.stats.pearsonr(data['Alcohol'],data['Proline']))

(0.6437200371782135, 3.288368689992126e-22)


## 2. Take any 5 features from the ‘wine.csv’ datasets and load them in a matrix. Thereafter, create the covariance matrix of the same.

In [18]:
col_list=["Alcohol","Malic.acid","Ash","Phenols","Flavanoids"]
fea=pd.read_csv('https://drive.google.com/uc?export=download&id=1EV_vQ1KSLiszmleCpGsFihloHNdimDRk',usecols=col_list)
print(fea)

     Alcohol  Malic.acid   Ash  Phenols  Flavanoids
0      14.23        1.71  2.43     2.80        3.06
1      13.20        1.78  2.14     2.65        2.76
2      13.16        2.36  2.67     2.80        3.24
3      14.37        1.95  2.50     3.85        3.49
4      13.24        2.59  2.87     2.80        2.69
..       ...         ...   ...      ...         ...
173    13.71        5.65  2.45     1.68        0.61
174    13.40        3.91  2.48     1.80        0.75
175    13.27        4.28  2.26     1.59        0.69
176    13.17        2.59  2.37     1.65        0.68
177    14.13        4.10  2.74     2.05        0.76

[178 rows x 5 columns]


In [19]:
covarience=np.cov(fea)
print(covarience)

[[27.77673  25.691305 24.53158  ... 25.28949  26.287185 26.891705]
 [25.691305 23.77698  22.702155 ... 23.54979  24.395635 25.013755]
 [24.53158  22.702155 21.70078  ... 22.601915 23.357885 23.97678 ]
 ...
 [25.28949  23.54979  22.601915 ... 26.23237  25.97693  27.49234 ]
 [26.287185 24.395635 23.357885 ... 25.97693  26.30912  27.44911 ]
 [26.891705 25.013755 23.97678  ... 27.49234  27.44911  28.91423 ]]
